'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.Resources", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address.
        '''</summary>
        Friend Shared ReadOnly Property Address() As String
            Get
                Return ResourceManager.GetString("Address", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Age.
        '''</summary>
        Friend Shared ReadOnly Property Age() As String
            Get
                Return ResourceManager.GetString("Age", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Birthdate.
        '''</summary>
        Friend Shared ReadOnly Property Birthdate() As String
            Get
                Return ResourceManager.GetString("Birthdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to City.
        '''</summary>
        Friend Shared ReadOnly Property City() As String
            Get
                Return ResourceManager.GetString("City", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Country.
        '''</summary>
        Friend Shared ReadOnly Property Country() As String
            Get
                Return ResourceManager.GetString("Country", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DrillingFor.
        '''</summary>
        Friend Shared ReadOnly Property Drilling() As String
            Get
                Return ResourceManager.GetString("Drilling", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email Address.
        '''</summary>
        Friend Shared ReadOnly Property EmailAddress() As String
            Get
                Return ResourceManager.GetString("EmailAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Employer.
        '''</summary>
        Friend Shared ReadOnly Property Employer() As String
            Get
                Return ResourceManager.GetString("Employer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Employer Data.
        '''</summary>
        Friend Shared ReadOnly Property EmployerData() As String
            Get
                Return ResourceManager.GetString("EmployerData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Employer Phone.
        '''</summary>
        Friend Shared ReadOnly Property EmployerPhone() As String
            Get
                Return ResourceManager.GetString("EmployerPhone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Encounter Date.
        '''</summary>
        Friend Shared ReadOnly Property EncounterDate() As String
            Get
                Return ResourceManager.GetString("EncounterDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Encounter Time.
        '''</summary>
        Friend Shared ReadOnly Property EncounterTime() As String
            Get
                Return ResourceManager.GetString("EncounterTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Name.
        '''</summary>
        Friend Shared ReadOnly Property FirstName() As String
            Get
                Return ResourceManager.GetString("FirstName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hire Date.
        '''</summary>
        Friend Shared ReadOnly Property HireDate() As String
            Get
                Return ResourceManager.GetString("HireDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Home Phone.
        '''</summary>
        Friend Shared ReadOnly Property HomePhone() As String
            Get
                Return ResourceManager.GetString("HomePhone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Incomplete Encounters.
        '''</summary>
        Friend Shared ReadOnly Property IncompleteEncounters() As String
            Get
                Return ResourceManager.GetString("IncompleteEncounters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Job Title.
        '''</summary>
        Friend Shared ReadOnly Property JobTitle() As String
            Get
                Return ResourceManager.GetString("JobTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Name.
        '''</summary>
        Friend Shared ReadOnly Property LastName() As String
            Get
                Return ResourceManager.GetString("LastName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Location.
        '''</summary>
        Friend Shared ReadOnly Property Location() As String
            Get
                Return ResourceManager.GetString("Location", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Medical Information.
        '''</summary>
        Friend Shared ReadOnly Property MedicalInfo() As String
            Get
                Return ResourceManager.GetString("MedicalInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Notes.
        '''</summary>
        Friend Shared ReadOnly Property Notes() As String
            Get
                Return ResourceManager.GetString("Notes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Patient Data.
        '''</summary>
        Friend Shared ReadOnly Property PatientData() As String
            Get
                Return ResourceManager.GetString("PatientData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Patient Information.
        '''</summary>
        Friend Shared ReadOnly Property PatientInfo() As String
            Get
                Return ResourceManager.GetString("PatientInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rig.
        '''</summary>
        Friend Shared ReadOnly Property Rig() As String
            Get
                Return ResourceManager.GetString("Rig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sex.
        '''</summary>
        Friend Shared ReadOnly Property Sex() As String
            Get
                Return ResourceManager.GetString("Sex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SSN/Passport #.
        '''</summary>
        Friend Shared ReadOnly Property SSN_Passport() As String
            Get
                Return ResourceManager.GetString("SSN_Passport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State.
        '''</summary>
        Friend Shared ReadOnly Property State() As String
            Get
                Return ResourceManager.GetString("State", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zip.
        '''</summary>
        Friend Shared ReadOnly Property Zip() As String
            Get
                Return ResourceManager.GetString("Zip", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
