'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3031
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class JobSheetInfo

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''litRigName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litRigName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litProjectNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litProjectNumber As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litRigPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litRigPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litAltPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAltPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litRigFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litRigFax As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litFacilityType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litFacilityType As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBlock As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLatitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litLatitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLongitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litLongitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litMedic1Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMedic1Name As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litMedic1Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMedic1Email As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litMedic1HomePhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMedic1HomePhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litMedic1CellPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMedic1CellPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litMedic2Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMedic2Name As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litMedic2HomePhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMedic2HomePhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litMedic2CellPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMedic2CellPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litMedic2Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMedic2Email As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litOIM1Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litOIM1Name As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litOIM1Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litOIM1Address As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litOIM1Phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litOIM1Phone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litOIM1CityStateZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litOIM1CityStateZip As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litOIM2Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litOIM2Name As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litOIM2Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litOIM2Address As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litOIM2Phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litOIM2Phone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litOIM2CityStateZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litOIM2CityStateZip As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLocMgrName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litLocMgrName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLocMgrAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litLocMgrAddress As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLocMgrPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litLocMgrPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litLocMgrCityStateZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litLocMgrCityStateZip As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litRigCompName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litRigCompName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litRigCompAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litRigCompAddress As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litRigCompPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litRigCompPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litRigCompCityStateZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litRigCompCityStateZip As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litFax As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEmpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEmpName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEmpAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEmpAddress As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEmpPhoneNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEmpPhoneNumber As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEmpCityStateZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEmpCityStateZip As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEmpAltPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEmpAltPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEmpFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEmpFax As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEmpContactName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEmpContactName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litCompMan1Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCompMan1Name As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litCompMan1Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCompMan1Address As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litCompMan1Phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCompMan1Phone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litCompMan1CityStateZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCompMan1CityStateZip As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litCompMan2Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCompMan2Name As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litCompMan2Address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCompMan2Address As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litCompMan2Phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCompMan2Phone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litCompMan2CityStateZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCompMan2CityStateZip As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litHeliName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litHeliName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litHeliAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litHeliAddress As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litHeliContactName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litHeliContactName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litHeliCityStateZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litHeliCityStateZip As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litHeliPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litHeliPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litHeliFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litHeliFax As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litHeliLongitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litHeliLongitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litHeliLatitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litHeliLatitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBoatName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBoatName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBoatAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBoatAddress As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBoatContactName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBoatContactName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBoatCityStateZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBoatCityStateZip As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBoatPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBoatPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBoatFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBoatFax As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBoatLongitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBoatLongitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBoatLatitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBoatLatitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacNmcName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacNmcName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacNmcDistance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacNmcDistance As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacNmcTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacNmcTime As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacNmcCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacNmcCity As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacNmcPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacNmcPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacNmcState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacNmcState As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacNmcAltPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacNmcAltPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacNmcFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacNmcFax As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacNmcLongitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacNmcLongitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacNmcLatitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacNmcLatitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC1Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC1Name As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC1Distance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC1Distance As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC1Time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC1Time As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC1City control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC1City As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC1Phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC1Phone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC1State control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC1State As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC1AltPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC1AltPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC1Fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC1Fax As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC1Longitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC1Longitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC1Latitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC1Latitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC2Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC2Name As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC2Distance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC2Distance As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC2Time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC2Time As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC2City control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC2City As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC2Phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC2Phone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC2State control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC2State As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC2AltPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC2AltPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC2Fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC2Fax As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC2Longitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC2Longitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacMC2Latitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacMC2Latitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacCGName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacCGName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacCGDistance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacCGDistance As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacCGTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacCGTime As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacCGCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacCGCity As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacCGPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacCGPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacCGtate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacCGtate As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacCGAltPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacCGAltPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacCGFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacCGFax As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacCGLongitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacCGLongitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEvacCGLatitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEvacCGLatitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litAmbName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAmbName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litAmbDistance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAmbDistance As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litAmbTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAmbTime As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litAmbCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAmbCity As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litAmbPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAmbPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litAmbState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAmbState As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litAmbAltPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAmbAltPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litAmbFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAmbFax As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litAmbLongitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAmbLongitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litAmbLatitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAmbLatitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma1Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma1Name As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma1Distance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma1Distance As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma1Time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma1Time As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma1CityState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma1CityState As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma1Phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma1Phone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma1RadFreq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma1RadFreq As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma1AltPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma1AltPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma1Fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma1Fax As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma1Longitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma1Longitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma1Latitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma1Latitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma2Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma2Name As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma2Distance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma2Distance As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma2Time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma2Time As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma2CityState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma2CityState As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma2Phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma2Phone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma2RadFreq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma2RadFreq As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma2AltPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma2AltPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma2Fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma2Fax As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma2Longitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma2Longitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litTrauma2Latitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litTrauma2Latitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBurnName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBurnName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBurnDistance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBurnDistance As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBurnTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBurnTime As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBurnCityState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBurnCityState As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBurnPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBurnPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBurnRadFreq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBurnRadFreq As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBurnAltPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBurnAltPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBurnFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBurnFax As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBurnLongitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBurnLongitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litBurnLatitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litBurnLatitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litClinicName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litClinicName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litClinicDistance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litClinicDistance As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litClinicTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litClinicTime As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litClinicCityState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litClinicCityState As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litClinicPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litClinicPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litClinicRadFreq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litClinicRadFreq As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litClinicAltPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litClinicAltPhone As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litClinicFax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litClinicFax As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litClinicLongitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litClinicLongitude As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litClinicLatitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litClinicLatitude As Global.System.Web.UI.WebControls.Literal
End Class
